### ISSUE TITLE
SVG Images Not Appearing on Site

### ISSUE THREAD

**Issue by misfist** [public-accountability/littlesis-news-theme#14]
SVG images are not appearing on site and showing as 404 error. The images are there. 

Can you verify that nginx is set up to serve SVG images?

Example:
https://github.com/public-accountability/littlesis-news-theme/blob/master/images/search.svg
https://news.littlesis.org/wp-content/themes/littlesis/images/search.svg

**Comment by misfist** [comment]
@aepyornis 

Could you also check on this? The search and social media icons, which are SVGs, don't show up right now.

**Comment by aepyornis** [comment]
https://news.littlesis.org/wp-content/themes/littlesis/images/search.svg seems to load okay

**Comment by misfist** [comment]
This may have been permissions-related also.
